#!/bin/sh
# This "jet" script is the command-line interface to all of JET.

# all variables set in the config file will be added to the environment
# settings in the local "jet.config" will override those in "~/.jetrc"

for i in $HOME/.jetrc jet.config jet-dev.config; do
    if [ -r $i ]; then
        echo loading $i
        set -a -e
        . $i
        set +a +e
    fi
done

# TODO dev build is called hub, goxc builds are called jethub
exec hub "$@"
