#!/bin/sh
# This "jet" script is the main command-line interface of JET.
# See https://github.com/jeelabs/jet

set -e  # exit on any command failure

# the default order and location for the configuration file is as follows:
#   $HOME/.jetrc
#   $HUBRUN/jet.config
#   $HUBRUN/jet-dev.config
# each next config file can override earlier settings
#
# the default value for $HUBRUN is
#   $GOPATH/src/github.com/jeelabs/jet/run
# add a HUBRUN=... line to your config file to change this

for i in .jetrc jet.config jet-dev.config; do
    c=${HUBRUN:-"$HOME"}/$i
    if [ -r $c ]; then
        echo loading $c
        . $c
    fi
    # this assumes that the $GOPATH variable contains a single path
    : ${HUBRUN:="$GOPATH/src/github.com/jeelabs/jet/run"}
done

# additional defaults

: ${HUBEXE:="`dirname $HUBRUN`/build/jethub"}
: ${HUBDEF:="$HUBRUN/hub.def"}

usage () {
    cat <<EOF

Usage:
  jet start     - start the hub in the background, if not yet running
  jet status    - display the last line of the log file
  jet stop      - stop the hub server (sends it a SIGTERM signal)
  jet quit      - abort the hub server (sends it a SIGQUIT signal)
  jet (reload|version) ...

Options:
`$HUBEXE help 2>&1`

Configuration:
  HUBEXE = $HUBEXE
  HUBRUN = $HUBRUN
  HUBDEF = $HUBDEF

EOF
}

case ${1:-"help"} in
    help) usage ;;
    status) tail -1 $HUBRUN/hub.log ;;
    *) exec $HUBEXE -r $HUBRUN -d $HUBDEF "$@" ;;
esac
