// Generated by CoffeeScript 1.8.0
(function() {
  var ng;

  ng = angular.module('DoodleApp', ['websocket']);

  ng.controller('DoodleCtrl', function($scope, $timeout, $websocket) {
    var ws, wsProto;
    wsProto = "https:" === document.location.protocol ? "wss" : "ws";
    ws = $websocket.connect("" + wsProto + "://" + location.hostname + ":1111/ws", ["jet"]);
    ws.register('', function(topic, body) {
      return console.log('mqtt:', topic, body);
    });
    $timeout(function() {
      return ws.emit('/doodle', [1, 2, 3]);
    }, 1000);
    $timeout(function() {
      return ws.emit('/doodledah', [4, 5, 6]);
    }, 2000);
    return $timeout(function() {
      return ws.emit('/doodle/dah', [7, 8, 9]);
    }, 3000);
  });

}).call(this);


//# sourceMappingURL=doodle.js.map
