// Generated by CoffeeScript 1.8.0
(function() {
  var client, mqtt, msgpack;

  console.log('Dump of all hub messages:');

  mqtt = require('mqtt');

  msgpack = require('msgpack');

  client = mqtt.connect('localhost', {
    keepalive: 300
  });

  client.on('error', function(e) {
    return console.log('error:', e);
  });

  client.on('connect', function() {
    console.log('connect:', Date());
    return client.subscribe('#');
  });

  client.on('message', function(topic, payload) {
    return console.log(topic, JSON.stringify(msgpack.unpack(payload)));
  });

}).call(this);


//# sourceMappingURL=dump.js.map
