// Generated by CoffeeScript 1.8.0
(function() {
  var client, mqtt, msgpack;

  console.log('Dump of all hub messages:');

  mqtt = require('mqtt');

  msgpack = require('msgpack');

  client = mqtt.connect('localhost', {
    keepalive: 0
  });

  client.subscribe('#');

  client.on('message', function(topic, payload) {
    return console.log(topic, JSON.stringify(msgpack.unpack(payload)));
  });

}).call(this);
