// Generated by CoffeeScript 1.8.0
(function() {
  var client, mqtt, msgpack;

  console.log('Dump of all hub messages:');

  mqtt = require('mqtt');

  msgpack = require('msgpack');

  client = mqtt.connect('localhost', {
    keepalive: 3600
  });

  client.on('error', function(e) {
    return console.log('error:', e);
  });

  client.on('connect', function() {
    console.log('connect:', Date());
    return client.subscribe('#');
  });

  client.on('message', function(topic, payload, packet) {
    var limit, s;
    if (packet.retain) {
      topic = 'R: ' + topic;
    }
    s = JSON.stringify(msgpack.unpack(payload));
    limit = 78 - topic.length;
    if (limit < 20) {
      limit = 20;
    }
    if (s.length > limit) {
      s = s.substr(0, limit - 3) + '...';
    } else {
      s = s.substr(0, limit);
    }
    s = s.replace(/[\x00-\x1F\x7F-\xFF]/g, '?');
    return console.log(topic, s);
  });

}).call(this);


//# sourceMappingURL=dump.js.map
