// Generated by CoffeeScript 1.8.0
(function() {
  var app;

  app = angular.module('MyApp', ['websocket']);

  app.run(function($rootScope) {
    return $rootScope.dummyMsg = 'JET says hello...';
  });

  app.controller('MainCtrl', function($scope, $timeout, $websocket) {
    var ws, wsProto;
    wsProto = "https:" === document.location.protocol ? "wss" : "ws";
    ws = $websocket.connect("" + wsProto + "://" + location.hostname + ":1111/ws", ["jet"]);
    ws.register('/haha', function(topic, body) {
      return console.log('ws1 got:', topic, body);
    });
    ws.register('/haha', function(topic, body) {
      return console.log('ws2 got:', topic, body);
    }, {
      exact: true
    });
    $timeout(function() {
      return ws.emit('/haha', [1, 2, 3]);
    }, 1000);
    $timeout(function() {
      return ws.emit('/hahaha', [4, 5, 6]);
    }, 2000);
    return $timeout(function() {
      return ws.emit('/haha/ha', [7, 8, 9]);
    }, 3000);
  });

}).call(this);


//# sourceMappingURL=app.js.map
