#!/bin/sh

###############################################################################
# >>> This is an example: copy as "jet" to your PATH and adjust as needed <<< #
###############################################################################

# jet -- Command-line admin interface to a running JET/Hub instance
# 
# Needs to know where a local copy of the hub binary is ($PROG) and where the
# real hub is running ($MQTT) - it can be either a local or a remote instance.
#
# Note: this command never starts up a new hub, it's ONLY an admin front-end!

PROG="$(dirname $0)/hub"
MQTT="tcp://127.0.0.1:1883"

# all arguments specified on the command line are passed command the admin mode
exec "$PROG" -admin $MQTT "$@"
